package awgconf

import (
	"net/netip"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
)

const (
	privB64 = "yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk="
	pubB64  = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg="
	pskB64  = "FpCyhws9cxwWoV4xELtfJvjJN+zQVRPISllRWgeopVE="
)

const providerConf = `# Generated by a provider
[Interface]
PrivateKey = ` + privB64 + `
Address = 10.8.1.7/32, fd00::7/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1380
Jc = 4
Jmin = 40
Jmax = 70
S1 = 15
S2 = 25
S3 = 10
S4 = 8
H1 = 100-200
H2 = 300-400
H3 = 500-600
H4 = 700-800
I1 = <b 0xc000000001><r 64><t>
I2 = <rd 12><rc 8>
Table = off
PostUp = echo up

[Peer]
PublicKey = ` + pubB64 + `
PresharedKey = ` + pskB64 + `
Endpoint = vpn.example.org:51820 # trailing comment
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
`

func mustPrefix(t *testing.T, s string) netip.Prefix {
	t.Helper()
	return netip.MustParsePrefix(s)
}

func TestParseProviderConfig(t *testing.T) {
	cfg, err := Parse(strings.NewReader(providerConf))
	if err != nil {
		t.Fatal(err)
	}
	priv, _ := ParseKey(privB64)
	pub, _ := ParseKey(pubB64)
	psk, _ := ParseKey(pskB64)
	want := &Config{
		Interface: Interface{
			PrivateKey: priv,
			Addresses:  []netip.Prefix{mustPrefix(t, "10.8.1.7/32"), mustPrefix(t, "fd00::7/128")},
			DNS:        []netip.Addr{netip.MustParseAddr("1.1.1.1"), netip.MustParseAddr("1.0.0.1")},
			MTU:        1380,
			Params: Params{
				Jc: 4, Jmin: 40, Jmax: 70,
				S1: 15, S2: 25, S3: 10, S4: 8,
				H1: Range{100, 200}, H2: Range{300, 400}, H3: Range{500, 600}, H4: Range{700, 800},
				I: [5]string{"<b 0xc000000001><r 64><t>", "<rd 12><rc 8>"},
			},
		},
		Peers: []Peer{{
			PublicKey:           pub,
			PresharedKey:        psk,
			Endpoint:            "vpn.example.org:51820",
			AllowedIPs:          []netip.Prefix{mustPrefix(t, "0.0.0.0/0"), mustPrefix(t, "::/0")},
			PersistentKeepalive: 25,
		}},
	}
	if diff := cmp.Diff(want, cfg, cmpopts.EquateComparable(netip.Prefix{}, netip.Addr{})); diff != "" {
		t.Errorf("Parse mismatch (-want +got):\n%s", diff)
	}
}

func TestParseLegacy15Config(t *testing.T) {
	const conf = `[Interface]
PrivateKey = ` + privB64 + `
Address = 10.0.0.2
Jc = 5
Jmin = 50
Jmax = 1000
S1 = 61
S2 = 24
H1 = 1234567
H2 = 2345678
H3 = 3456789
H4 = 4567890

[Peer]
PublicKey = ` + pubB64 + `
Endpoint = 203.0.113.5:443
AllowedIPs = 0.0.0.0/0
`
	cfg, err := Parse(strings.NewReader(conf))
	if err != nil {
		t.Fatal(err)
	}
	if got := cfg.Interface.Addresses; len(got) != 1 || got[0] != mustPrefix(t, "10.0.0.2/32") {
		t.Errorf("bare address not widened to /32: %v", got)
	}
	if cfg.Interface.H1 != (Range{1234567, 1234567}) {
		t.Errorf("single H1 = %v", cfg.Interface.H1)
	}
	if cfg.Interface.S3 != 0 || cfg.Interface.S4 != 0 {
		t.Errorf("S3/S4 should stay zero: %d %d", cfg.Interface.S3, cfg.Interface.S4)
	}
}

func TestParseErrors(t *testing.T) {
	cases := map[string]string{
		"unknown interface key": "[Interface]\nPrivateKey = " + privB64 + "\nHeaderProtectionKey = abc\n",
		"unknown peer key":      "[Interface]\nPrivateKey = " + privB64 + "\n[Peer]\nPublicKey = " + pubB64 + "\nFoo = 1\n",
		"missing private key":   "[Interface]\nAddress = 10.0.0.2/32\n",
		"bad key length":        "[Interface]\nPrivateKey = AAAA\n",
		"bad range":             "[Interface]\nPrivateKey = " + privB64 + "\nH1 = 200-100\n",
		"key outside section":   "PrivateKey = " + privB64 + "\n",
		"unknown section":       "[Foo]\n",
		"no equals":             "[Interface]\nPrivateKey\n",
		"bad address":           "[Interface]\nPrivateKey = " + privB64 + "\nAddress = nope\n",
	}
	for name, conf := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := Parse(strings.NewReader(conf)); err == nil {
				t.Fatal("expected error")
			}
		})
	}
}

func TestRoundTrip(t *testing.T) {
	cfg, err := Parse(strings.NewReader(providerConf))
	if err != nil {
		t.Fatal(err)
	}
	again, err := Parse(strings.NewReader(cfg.String()))
	if err != nil {
		t.Fatalf("re-parse of rendered config: %v\n%s", err, cfg.String())
	}
	if diff := cmp.Diff(cfg, again, cmpopts.EquateComparable(netip.Prefix{}, netip.Addr{})); diff != "" {
		t.Errorf("round trip mismatch (-first +second):\n%s", diff)
	}
}

func TestUAPI(t *testing.T) {
	cfg, err := Parse(strings.NewReader(providerConf))
	if err != nil {
		t.Fatal(err)
	}
	priv, _ := ParseKey(privB64)
	pub, _ := ParseKey(pubB64)
	psk, _ := ParseKey(pskB64)
	want := "private_key=" + priv.Hex() + "\n" +
		"jc=4\njmin=40\njmax=70\n" +
		"s1=15\ns2=25\ns3=10\ns4=8\n" +
		"h1=100-200\nh2=300-400\nh3=500-600\nh4=700-800\n" +
		"i1=<b 0xc000000001><r 64><t>\ni2=<rd 12><rc 8>\n" +
		"public_key=" + pub.Hex() + "\n" +
		"preshared_key=" + psk.Hex() + "\n" +
		"endpoint=vpn.example.org:51820\n" +
		"replace_allowed_ips=true\n" +
		"allowed_ip=0.0.0.0/0\nallowed_ip=::/0\n" +
		"persistent_keepalive_interval=25\n"
	if diff := cmp.Diff(want, cfg.UAPI()); diff != "" {
		t.Errorf("UAPI mismatch (-want +got):\n%s", diff)
	}
}

func TestRange(t *testing.T) {
	for in, want := range map[string]string{"5": "5", "5-9": "5-9", " 7 - 8 ": "7-8"} {
		r, err := ParseRange(in)
		if err != nil {
			t.Errorf("ParseRange(%q): %v", in, err)
			continue
		}
		if r.String() != want {
			t.Errorf("ParseRange(%q).String() = %q, want %q", in, r.String(), want)
		}
	}
}

func TestKeys(t *testing.T) {
	priv, err := GeneratePrivateKey()
	if err != nil {
		t.Fatal(err)
	}
	if priv[0]&7 != 0 || priv[31]&128 != 0 || priv[31]&64 == 0 {
		t.Error("private key is not clamped")
	}
	parsed, err := ParseKey(priv.String())
	if err != nil || parsed != priv {
		t.Errorf("base64 round trip failed: %v", err)
	}
	if priv.Public() != priv.Public() || priv.Public() == priv {
		t.Error("public key derivation is not deterministic or equals private key")
	}
	if len(priv.Hex()) != 64 {
		t.Errorf("hex length %d", len(priv.Hex()))
	}
}
